print("1Alien Hammer")
print("2Ancient Blade")
print("3Angelic Hammer")
print("4Bandit Sword")
print("5Bat Scythe")
print("6Blizzard Striker")
print("7Bluesteel Sword")
print("8Bone Sword")
print("9Bronze")
print("10Chaos Arcane")
print("11Chaotic Blade")
print("12Chaotic Hammer")
print("13Cleaver Blade")
print("14Crimson Arcane")
print("15Crimson Blade")
print("16Dark Katana")
print("17Dark Steel Blade")
print("18DarkAxe")
print("19Diamond")
print("20Diamond Edge")
print("21Dragon Blade")
print("22DragonAxe")
print("23Element Sword")
print("24Emerald Edge")
print("25Emerald Hammer")
print("26Fallen Blade")
print("27Fire Arcane")
print("28Fire Blade")
print("29Fire Dagger")
print("30Flame Hammer")
print("31Frostbrand")
print("32Gold")
print("33Heavenly Blade")
print("34Ice Hammer")
print("35Ice Sword")
print("36Iron")
print("37Laser Scythe")
print("38Lava Blade")
print("39Lighting Blade")
print("40Magma Sword")
print("41Morrow Sword")
print("42Mystic Arcane")
print("43Mythic Sword")
print("44Nefertiti Sword")
print("45Oblivion")
print("46Omega Blade")
print("47Omega Slicer")
print("48Overseer Axe")
print("49Phoenix Blade")
print("50Polished Blade")
print("51Scaled Sword")
print("52SerpentineAxe")
print("53Singularity Scythe")
print("54Skull Basher")
print("55Slicer")
print("56Snake Arcane")
print("57Space Omega")
print("58Spider Slasher")
print("59Steel")
print("60Sun Axe")
print("61Sword of Darkness")
print("62Sword of the Behemoth")
print("63The Devil's Blade")
print("64The Sorcus")
print("65Titan's Hammer")
print("66Vilethorn")
print("67Volcanic Slicer")
print("68Warlord's Wrath")
print("69Winged Sword")
print("70knight Blade")
